// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/messenger/v1/messenger_v1.proto

package messenger_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SEND_ENVELOPE_STATUS int32

const (
	SEND_ENVELOPE_STATUS_ERROR     SEND_ENVELOPE_STATUS = 0
	SEND_ENVELOPE_STATUS_DELIVERED SEND_ENVELOPE_STATUS = 1
)

// Enum value maps for SEND_ENVELOPE_STATUS.
var (
	SEND_ENVELOPE_STATUS_name = map[int32]string{
		0: "ERROR",
		1: "DELIVERED",
	}
	SEND_ENVELOPE_STATUS_value = map[string]int32{
		"ERROR":     0,
		"DELIVERED": 1,
	}
)

func (x SEND_ENVELOPE_STATUS) Enum() *SEND_ENVELOPE_STATUS {
	p := new(SEND_ENVELOPE_STATUS)
	*p = x
	return p
}

func (x SEND_ENVELOPE_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SEND_ENVELOPE_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_messenger_v1_messenger_v1_proto_enumTypes[0].Descriptor()
}

func (SEND_ENVELOPE_STATUS) Type() protoreflect.EnumType {
	return &file_proto_messenger_v1_messenger_v1_proto_enumTypes[0]
}

func (x SEND_ENVELOPE_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SEND_ENVELOPE_STATUS.Descriptor instead.
func (SEND_ENVELOPE_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_proto_messenger_v1_messenger_v1_proto_rawDescGZIP(), []int{0}
}

type Conversation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token        string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Conversation string `protobuf:"bytes,2,opt,name=conversation,proto3" json:"conversation,omitempty"`
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_messenger_v1_messenger_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messenger_v1_messenger_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_proto_messenger_v1_messenger_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Conversation) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Conversation) GetConversation() string {
	if x != nil {
		return x.Conversation
	}
	return ""
}

type NewEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender       string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Conversation string `protobuf:"bytes,2,opt,name=conversation,proto3" json:"conversation,omitempty"`
	Message      string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *NewEnvelope) Reset() {
	*x = NewEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_messenger_v1_messenger_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewEnvelope) ProtoMessage() {}

func (x *NewEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messenger_v1_messenger_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewEnvelope.ProtoReflect.Descriptor instead.
func (*NewEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_messenger_v1_messenger_v1_proto_rawDescGZIP(), []int{1}
}

func (x *NewEnvelope) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *NewEnvelope) GetConversation() string {
	if x != nil {
		return x.Conversation
	}
	return ""
}

func (x *NewEnvelope) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Envelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Sender  string               `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Message string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Status  SEND_ENVELOPE_STATUS `protobuf:"varint,4,opt,name=status,proto3,enum=messenger.SEND_ENVELOPE_STATUS" json:"status,omitempty"`
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_messenger_v1_messenger_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messenger_v1_messenger_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_messenger_v1_messenger_v1_proto_rawDescGZIP(), []int{2}
}

func (x *Envelope) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Envelope) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Envelope) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Envelope) GetStatus() SEND_ENVELOPE_STATUS {
	if x != nil {
		return x.Status
	}
	return SEND_ENVELOPE_STATUS_ERROR
}

var File_proto_messenger_v1_messenger_v1_proto protoreflect.FileDescriptor

var file_proto_messenger_v1_messenger_v1_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65,
	0x72, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x5f, 0x76,
	0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67,
	0x65, 0x72, 0x22, 0x48, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x63, 0x0a, 0x0b,
	0x4e, 0x65, 0x77, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x76, 0x65,
	0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x87, 0x01, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x53,
	0x45, 0x4e, 0x44, 0x5f, 0x45, 0x4e, 0x56, 0x45, 0x4c, 0x4f, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x30, 0x0a, 0x14, 0x53,
	0x45, 0x4e, 0x44, 0x5f, 0x45, 0x4e, 0x56, 0x45, 0x4c, 0x4f, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x44, 0x45, 0x4c, 0x49, 0x56, 0x45, 0x52, 0x45, 0x44, 0x10, 0x01, 0x32, 0x98, 0x01,
	0x0a, 0x10, 0x4d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65,
	0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x13,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x76, 0x65, 0x6c,
	0x6f, 0x70, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3f, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x45,
	0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e,
	0x67, 0x65, 0x72, 0x2e, 0x4e, 0x65, 0x77, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x1a,
	0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x22, 0x00, 0x28, 0x01, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x72, 0x65, 0x76, 0x61, 0x74, 0x6b, 0x2f, 0x67,
	0x6f, 0x2d, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_messenger_v1_messenger_v1_proto_rawDescOnce sync.Once
	file_proto_messenger_v1_messenger_v1_proto_rawDescData = file_proto_messenger_v1_messenger_v1_proto_rawDesc
)

func file_proto_messenger_v1_messenger_v1_proto_rawDescGZIP() []byte {
	file_proto_messenger_v1_messenger_v1_proto_rawDescOnce.Do(func() {
		file_proto_messenger_v1_messenger_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_messenger_v1_messenger_v1_proto_rawDescData)
	})
	return file_proto_messenger_v1_messenger_v1_proto_rawDescData
}

var file_proto_messenger_v1_messenger_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_messenger_v1_messenger_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_messenger_v1_messenger_v1_proto_goTypes = []interface{}{
	(SEND_ENVELOPE_STATUS)(0), // 0: messenger.SEND_ENVELOPE_STATUS
	(*Conversation)(nil),      // 1: messenger.Conversation
	(*NewEnvelope)(nil),       // 2: messenger.NewEnvelope
	(*Envelope)(nil),          // 3: messenger.Envelope
}
var file_proto_messenger_v1_messenger_v1_proto_depIdxs = []int32{
	0, // 0: messenger.Envelope.status:type_name -> messenger.SEND_ENVELOPE_STATUS
	1, // 1: messenger.MessengerService.StreamEnvelopes:input_type -> messenger.Conversation
	2, // 2: messenger.MessengerService.SendEnvelope:input_type -> messenger.NewEnvelope
	3, // 3: messenger.MessengerService.StreamEnvelopes:output_type -> messenger.Envelope
	3, // 4: messenger.MessengerService.SendEnvelope:output_type -> messenger.Envelope
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_messenger_v1_messenger_v1_proto_init() }
func file_proto_messenger_v1_messenger_v1_proto_init() {
	if File_proto_messenger_v1_messenger_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_messenger_v1_messenger_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Conversation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_messenger_v1_messenger_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_messenger_v1_messenger_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Envelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_messenger_v1_messenger_v1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_messenger_v1_messenger_v1_proto_goTypes,
		DependencyIndexes: file_proto_messenger_v1_messenger_v1_proto_depIdxs,
		EnumInfos:         file_proto_messenger_v1_messenger_v1_proto_enumTypes,
		MessageInfos:      file_proto_messenger_v1_messenger_v1_proto_msgTypes,
	}.Build()
	File_proto_messenger_v1_messenger_v1_proto = out.File
	file_proto_messenger_v1_messenger_v1_proto_rawDesc = nil
	file_proto_messenger_v1_messenger_v1_proto_goTypes = nil
	file_proto_messenger_v1_messenger_v1_proto_depIdxs = nil
}
